version: "3.9"

services:
  db:
    image: mariadb:10
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: somewordpress
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress
  wordpress:
    depends_on:
      - db
    image: wordpress
    volumes:
      - ./wordpress_data:/var/www/html
      - ./upload.ini:/usr/local/etc/php/conf.d/uploads.ini
    ports:
      - "8000:80"
    restart: always
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
      WORDPRESS_DB_NAME: wordpress
  app:
    build:
      context: .
      dockerfile: DOCKERFILE
    ports:
      - "80:80"
    volumes:
      - ./app:/var/www/html
    depends_on:
      - db
      - wordpress
volumes:
  db_data:
    external:
      name: env-database


