version: "3.9"

services:
  db:
    image: mariadb:10
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    env_file:
      - .secret_env
    environment:
      MYSQL_ROOT_PASSWORD: ${ROOT_PASSWORD}
      MYSQL_DATABASE: wordpress
      MYSQL_USER: ${USERNAME}
      MYSQL_PASSWORD: ${PASSWORD}


  wordpress:
    depends_on:
      - db
    image: wordpress
    volumes:
      - ./wordpress_data:/var/www/html
      - ./upload.ini:/usr/local/etc/php/conf.d/uploads.ini
    ports:
      - "8000:80"
    restart: always
    env_file:
      - .secret_env
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: ${USERNAME}
      WORDPRESS_DB_PASSWORD: ${PASSWORD}
      WORDPRESS_DB_NAME: wordpress
  app:
    build:
      context: .
      dockerfile: DOCKERFILE
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./app:/var/www/html
    depends_on:
      - db
      - wordpress

volumes:
  db_data:




